import Testing
import AOCHelper
@testable import Day07

@Test
func sampleTest() throws {
    let input = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """
    let result = try Part1.process(input)
    #expect(result == "21")
}

@Test
func sampleTestPart2() throws {
    let input = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """
    let result = try Part2.process(input)
    #expect(result == "40")
}

@Test
func quantumTimelinesForSplitter() {
    let manifold = TachyonManifold(grid: .init(data: [
        [.empty, .splitter, .empty],
        [.empty, .empty, .empty]
    ]))

    var memo: [Vec2: Int] = [:]
    let result = manifold.quantumTimelines(memo: &memo, pos: Vec2(1, 0))
    #expect(result == 2)
}

@Test
func quantumTimelinesForMultipleSplitters() {
    let manifold = TachyonManifold(grid: .init(data: [
        [.empty, .empty,    .splitter, .empty,    .empty],
        [.empty, .splitter, .empty,    .splitter, .empty],
        [.empty, .empty,    .empty,    .empty,    .empty]
    ]))

    var memo: [Vec2: Int] = [:]
    let result = manifold.quantumTimelines(memo: &memo, pos: Vec2(2, 0))
    #expect(result == 4)
}
